services:
  axum:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
  mysql:
    image: mysql:8-oracle
    env_file:
      - .env
    command: mysqld --default_authentication_plugin=mysql_native_password
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
