[package]
edition = "2021"
name = "hello-world"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.5.6"
tokio = {version = "1.18.2", features = ["full"]}
